Fix the TOGETHER class
Summary:
Together API changes the field `model_name` to `model` now:
```
pydantic.v1.error_wrappers.ValidationError: 2 validation errors for Together
model
  field required (type=value_error.missing)
model_name
  extra fields not permitted (type=value_error.extra)
```
Hence make the update.

Reviewed By: spencerwmeta

Differential Revision: D51925200

fbshipit-source-id: fb285d0ace46c71d572ce1e401a14bf0c55bcedc